package dev.kourier.amqp.channel

import dev.kourier.amqp.*
import kotlinx.coroutines.channels.ReceiveChannel

interface AMQPChannel {

    /**
     * Unique identifier of the channel.
     */
    val id: ChannelId

    @InternalAmqpApi
    suspend fun <T : AMQPResponse> writeAndWaitForResponse(vararg frames: Frame): T

    /**
     * Closes the channel.
     *
     * @param reason Reason that can be logged by the broker.
     * @param code Code that can be logged by the broker.
     *
     * @return Nothing. The channel is closed synchronously.
     */
    fun close(
        reason: String = "",
        code: UShort = 200u,
    )

    /**
     * Publish a ByteArray message to exchange or queue.
     *
     * @param body Message payload that can be read from ByteArray.
     * @param exchange Name of exchange on which the message is published. Can be empty.
     * @param routingKey Name of routingKey that will be attached to the message.
     *        An exchange looks at the routingKey while deciding how the message has to be routed.
     *        When exchange parameter is empty routingKey is used as queueName.
     * @param mandatory When a published message cannot be routed to any queue and mandatory is true, the message will be returned to publisher.
     *        Returned message must be handled with returnListener or returnConsumer.
     *        When a published message cannot be routed to any queue and mandatory is false, the message is discarded or republished to an alternate exchange, if any.
     * @param immediate When matching queue has at least one or more consumers and immediate is set to true, message is delivered to them immediately.
     *        When matching queue has zero active consumers and immediate is set to true, message is returned to publisher.
     *        When matching queue has zero active consumers and immediate is set to false, message will be delivered to the queue.
     * @param properties Additional message properties (check amqp documentation).
     *
     * @return DeliveryTag waiting for message write to the broker.
     *         DeliveryTag is 0 when channel is not in confirm mode.
     *         DeliveryTag is > 0 (monotonically increasing) when channel is in confirm mode.
     */
    suspend fun basicPublish(
        body: ByteArray,
        exchange: String,
        routingKey: String,
        mandatory: Boolean = false,
        immediate: Boolean = false,
        properties: Properties = Properties(),
    ): AMQPResponse.Channel.Basic.Published

    /**
     * Get a single message from a queue.
     *
     * @param queue Name of the queue.
     * @param noAck Controls whether message will be acked or nacked automatically (`true`) or manually (`false`).
     * @return AMQPResponse.Channel.Message.Get? when queue is not empty, otherwise null.
     * @deprecated EventLoopFuture based public API will be removed in first stable release, please use Async API.
     */
    suspend fun basicGet(
        queue: String,
        noAck: Boolean = false,
    ): AMQPResponse.Channel.Message.Get

    /**
     * Consume messages from a queue by sending them to the channel.
     * The consumer is automatically canceled when the channel is closed.
     *
     * @param queue Name of the queue.
     * @param consumerTag Name of the consumer; if empty, will be generated by the broker.
     * @param noAck Controls whether message will be acked or nacked automatically (`true`) or manually (`false`).
     * @param exclusive Ensures that queue can only be consumed by a single consumer.
     * @param arguments Additional arguments (check RabbitMQ documentation).
     *
     * @return AMQPResponse.Channel.Basic.ConsumeOk confirming that broker has accepted the consume request.
     */
    suspend fun basicConsumeAsChannel(
        queue: String,
        consumerTag: String = "",
        noAck: Boolean = false,
        exclusive: Boolean = false,
        arguments: Table = Table(emptyMap()),
    ): ReceiveChannel<AMQPResponse.Channel.Message.Delivery>

    /**
     * Consume messages from a queue by sending them to registered consume listeners.
     * The caller is responsible for cancelling the consumer when done.
     *
     * @param queue Name of the queue.
     * @param consumerTag Name of the consumer; if empty, will be generated by the broker.
     * @param noAck Controls whether message will be acked or nacked automatically (`true`) or manually (`false`).
     * @param exclusive Ensures that queue can only be consumed by a single consumer.
     * @param arguments Additional arguments (check RabbitMQ documentation).
     * @param listener: Callback when Delivery arrives - automatically registered.
     *
     * @return AMQPResponse.Channel.Basic.ConsumeOk confirming that broker has accepted the consume request.
     */
    suspend fun basicConsume(
        queue: String,
        consumerTag: String = "",
        noAck: Boolean = false,
        exclusive: Boolean = false,
        arguments: Table = Table(emptyMap()),
        listener: (AMQPResponse.Channel.Message.Delivery) -> Unit,
    ): AMQPResponse.Channel.Basic.ConsumeOk

    /**
     * Consume messages from a queue by sending them to registered consume listeners.
     * The caller is responsible for cancelling the consumer when done.
     *
     * @param queue Name of the queue.
     * @param consumerTag Name of the consumer; if empty, will be generated by the broker.
     * @param noAck Controls whether message will be acked or nacked automatically (`true`) or manually (`false`).
     * @param exclusive Ensures that queue can only be consumed by a single consumer.
     * @param arguments Additional arguments (check RabbitMQ documentation).
     *
     * @return AMQPResponse.Channel.Basic.ConsumeOk confirming that broker has accepted the consume request.
     */
    suspend fun basicConsume(
        queue: String,
        consumerTag: String = "",
        noAck: Boolean = false,
        exclusive: Boolean = false,
        arguments: Table = Table(emptyMap()),
    ): AMQPResponse.Channel.Basic.ConsumeOk

    /**
     * Cancel sending messages from server to consumer.
     *
     * @param consumerTag Identifier of the consumer.
     *
     * @return AMQPResponse.Channel.Basic.Canceled confirming that broker has accepted the cancel request.
     */
    suspend fun basicCancel(
        consumerTag: String,
    ): AMQPResponse.Channel.Basic.Canceled

    /**
     * Acknowledge a message.
     *
     * @param deliveryTag Number (identifier) of the message.
     * @param multiple Controls whether only this message is acked (`false`) or additionally all others up to it (`true`).
     */
    suspend fun basicAck(
        deliveryTag: ULong,
        multiple: Boolean = false,
    )

    /**
     * Acknowledge a message.
     *
     * @param message Received message.
     * @param multiple Controls whether only this message is acked (`false`) or additionally all others up to it (`true`).
     */
    suspend fun basicAck(
        message: AMQPMessage,
        multiple: Boolean = false,
    )

    /**
     * Reject a message.
     *
     * @param deliveryTag Number (identifier) of the message.
     * @param multiple Controls whether only this message is rejected (`false`) or additionally all others up to it (`true`).
     * @param requeue Controls whether to requeue message after reject.
     */
    suspend fun basicNack(
        deliveryTag: ULong,
        multiple: Boolean = false,
        requeue: Boolean = false,
    )

    /**
     * Reject a message.
     *
     * @param message Received message.
     * @param multiple Controls whether only this message is rejected (`false`) or additionally all others up to it (`true`).
     * @param requeue Controls whether to requeue message after reject.
     */
    suspend fun basicNack(
        message: AMQPMessage,
        multiple: Boolean = false,
        requeue: Boolean = false,
    )

    /**
     * Reject a message.
     *
     * @param deliveryTag Number (identifier) of the message.
     * @param requeue Controls whether to requeue message after reject.
     */
    suspend fun basicReject(
        deliveryTag: ULong,
        requeue: Boolean = false,
    )

    /**
     * Reject a message.
     *
     * @param message Received Message.
     * @param requeue Controls whether to requeue message after reject.
     */
    suspend fun basicReject(
        message: AMQPMessage,
        requeue: Boolean = false,
    )

    /**
     * Tell the broker what to do with all unacknowledged messages.
     * Unacknowledged messages retrieved by `basicGet` are requeued regardless.
     *
     * @param requeue Controls whether to requeue all messages after rejecting them.
     * @return AMQPResponse.Channel.Basic.Recovered confirming that broker has accepted the recover request.
     */
    suspend fun basicRecover(
        requeue: Boolean = false,
    ): AMQPResponse.Channel.Basic.Recovered

    /**
     * Sets a prefetch limit when consuming messages.
     * No more messages will be delivered to the consumer until one or more messages have been acknowledged or rejected.
     *
     * @param count Size of the limit.
     * @param global Whether the limit will be shared across all consumers on the channel.
     *
     * @return AMQPResponse.Channel.Basic.QosOk confirming that broker has accepted the qos request.
     */
    suspend fun basicQos(
        count: UShort,
        global: Boolean = false,
    ): AMQPResponse.Channel.Basic.QosOk

    /**
     * Declares a queue.
     *
     * @param name Name of the queue.
     * @param passive If enabled, broker will raise exception if queue already exists.
     * @param durable If enabled, creates a queue stored on disk; otherwise, transient.
     * @param exclusive If enabled, queue will be deleted when the channel is closed.
     * @param autoDelete If enabled, queue will be deleted when the last consumer has stopped consuming.
     * @param arguments Additional arguments (check RabbitMQ documentation).
     *
     * @return AMQPResponse.Channel.Queue.Declared confirming that broker has accepted the request.
     */
    suspend fun queueDeclare(
        name: String,
        passive: Boolean = false,
        durable: Boolean = false,
        exclusive: Boolean = false,
        autoDelete: Boolean = false,
        arguments: Table = Table(emptyMap()),
    ): AMQPResponse.Channel.Queue.Declared

    /**
     * Deletes a queue.
     *
     * @param name Name of the queue.
     * @param ifUnused If enabled, queue will be deleted only when there are no consumers subscribed to it.
     * @param ifEmpty If enabled, queue will be deleted only when it's empty.
     *
     * @return AMQPResponse.Channel.Queue.Deleted confirming that broker has accepted the delete request.
     */
    suspend fun queueDelete(
        name: String,
        ifUnused: Boolean = false,
        ifEmpty: Boolean = false,
    ): AMQPResponse.Channel.Queue.Deleted

    /**
     * Deletes all messages from a queue.
     *
     * @param name Name of the queue.
     *
     * @return AMQPResponse.Channel.Queue.Purged confirming that broker has accepted the delete request.
     */
    suspend fun queuePurge(
        name: String,
    ): AMQPResponse.Channel.Queue.Purged

    /**
     * Binds a queue to an exchange.
     *
     * @param queue Name of the queue.
     * @param exchange Name of the exchange.
     * @param routingKey Bind only to messages matching routingKey.
     * @param arguments Bind only to messages matching given options.
     *
     * @return AMQPResponse.Channel.Queue.Bound confirming that broker has accepted the request.
     */
    suspend fun queueBind(
        queue: String,
        exchange: String,
        routingKey: String = "",
        arguments: Table = Table(emptyMap()),
    ): AMQPResponse.Channel.Queue.Bound

    /**
     * Unbinds a queue from an exchange.
     *
     * @param queue Name of the queue.
     * @param exchange Name of the exchange.
     * @param routingKey Unbind only from messages matching routingKey.
     * @param arguments Unbind only from messages matching given options.
     *
     * @return AMQPResponse.Channel.Queue.Unbound confirming that broker has accepted the unbind request.
     */
    suspend fun queueUnbind(
        queue: String,
        exchange: String,
        routingKey: String = "",
        arguments: Table = Table(emptyMap()),
    ): AMQPResponse.Channel.Queue.Unbound

    /**
     * Declare an exchange.
     *
     * @param name Name of the exchange.
     * @param type Type of the exchange.
     * @param passive If enabled, broker will raise exception if exchange already exists.
     * @param durable If enabled, creates an exchange stored on disk; otherwise, transient.
     * @param autoDelete If enabled, exchange will be deleted when the last consumer has stopped consuming.
     * @param internal Whether the exchange cannot be directly published to by client.
     * @param arguments Additional arguments (check RabbitMQ documentation).
     *
     * @return AMQPResponse.Channel.Exchange.Declared
     */
    suspend fun exchangeDeclare(
        name: String,
        type: String,
        passive: Boolean = false,
        durable: Boolean = false,
        autoDelete: Boolean = false,
        internal: Boolean = false,
        arguments: Table = Table(emptyMap()),
    ): AMQPResponse.Channel.Exchange.Declared

    /**
     * Delete an exchange.
     *
     * @param name Name of the exchange.
     * @param ifUnused If enabled, exchange will be deleted only when it is not used.
     *
     * @return AMQPResponse.Channel.Exchange.Deleted
     */
    suspend fun exchangeDelete(
        name: String,
        ifUnused: Boolean = false,
    ): AMQPResponse.Channel.Exchange.Deleted

    /**
     * Bind an exchange to another exchange.
     *
     * @param destination Output exchange.
     * @param source Input exchange.
     * @param routingKey Bind only to messages matching routingKey.
     * @param arguments Bind only to messages matching given options.
     *
     * @return AMQPResponse.Channel.Exchange.Bound
     */
    suspend fun exchangeBind(
        destination: String,
        source: String,
        routingKey: String,
        arguments: Table = Table(emptyMap()),
    ): AMQPResponse.Channel.Exchange.Bound

    /**
     * Unbind an exchange from another exchange.
     *
     * @param destination Output exchange.
     * @param source Input exchange.
     * @param routingKey Unbind only from messages matching routingKey.
     * @param arguments Unbind only from messages matching given options.
     *
     * @return AMQPResponse.Channel.Exchange.Unbound
     */
    suspend fun exchangeUnbind(
        destination: String,
        source: String,
        routingKey: String,
        arguments: Table = Table(emptyMap()),
    ): AMQPResponse.Channel.Exchange.Unbound

}
