name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    services:
      rabbitmq:
        image: rabbitmq:4.1
        ports: [ "5672:5672" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up our JDK environment
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Install dependencies and run tests
        run: ./gradlew jvmTest koverXmlReport
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
